---
- name: Mount media server folder only
  hosts: tag_media-server
  gather_facts: yes

  vars:
    s3fs_fuse_version: "1.80"
    s3fs_fuse_bucket: media-bucket
    s3fs_fuse_mount_point: "/mnt/s3"
    s3fs_fuse_mount_point_permissions: "0777"
    s3fs_fuse_url: "https://s3.fr-par.scw.cloud"
    s3fs_fuse_cache_folder: /tmp/cache
    s3fs_fuse_option_flags:
      - "allow_other"
      - "nonempty"
      - "umask=0002,uid=112,gid=115" # uid and gid must be plex user and group id
    s3fs_fuse_access_key_id: "{{vault_access_key_id}}"
    s3fs_fuse_secret_access_key: "{{vault_secret_access_key}}"

  roles:
  - role: s3fs-fuse
  - role: s3fs-fuse-clean
  - role: s3fs-cache-handler


